load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "checksum",
    srcs = ["checksum.cc"],
    hdrs = ["checksum.h"],
)

cc_binary(
    name = "checksum_tool",
    srcs = ["main.cc"],
    deps = [":checksum"],
)

cc_test(
    name = "checksum_test",
    size = "small",
    srcs = ["checksum_test.cc"],
    deps = [":checksum"],
)
